# Generated by Django 4.2.3 on 2023-07-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_on",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("recipe_name", models.CharField(max_length=100)),
                ("recipe_desc", models.TextField()),
                ("recipe_image", models.ImageField(upload_to="recipe_images")),
            ],
        ),
    ]
